### ISSUE TITLE
[TRG 2.05] Add .tractusx repository metadata

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/puris-frontend#36]
In our [release guideline 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) we describe a yaml metadata file that should be present for each of our repositories in eclipse-tractusx.

We are using this to automate several things across the GitHub org, like combining repos to a "Product view".
If the `.tractusx` metadata file is missing, we cannot show the repo in views like that

**Comment by tom-rm-meyer-ISST** [comment]
We're currently deprecating the frontend and [backend](https://github.com/eclipse-tractusx/puris-backend) repository to merge the two repositories into one. This was our idea to incorporate this TRG.

Please find attached the [PR](https://github.com/eclipse-tractusx/puris/pull/1).

We'll deprecate the separated repositories soon.

**Comment by FaGru3n** [comment]
@tom-rm-meyer-ISST  Cool, thx for mentioning 👍🏼 

Found a Hint for the PR https://github.com/eclipse-tractusx/puris/pull/1
> In the root of the [TRG 2.04 - Leading product repository](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) create a file called .tractusx:

currently for intit PR i found the `.tractusx` metafiles in each subfolder for front / backend

**Comment by tom-rm-meyer-ISST** [comment]
@FaGru3n should we place an additional file into the root directory or just replace the separated ones by one in three root directory? I guess the second approach is correct, isn't it?

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST the root one on leading repo `puris` is the important one, when the `backend` and `frontend` repo will still exist and than also the underlying repos must have metafiles.

``` yaml
product: "PRODUCT_NAME"
leadingRepository: "LEADING_PRODUCT_REPOSITORY_URL"
repositories:
  - name: "REPOSITORY_1_NAME"
    usage: "DESCRIPTION/PURPOSE"
    url: "REPOSITORY_1_URL"
  - name: "REPOSITORY_2_NAME"
    usage: "DESCRIPTION/PURPOSE"
    url: "REPOSITORY_2_URL"
```

but when you afterwards just have one puris repo you have to describe it whats needed for `backend` and `frontend` for puris
and the metafile shoul look like:

``` yaml
product: "Puris"
leadingRepository: "https://github.com/eclipse-tractusx/puris"
repositories:
- name: "puris"
  usage: "Puris Frontend and Backend implementaion"
  url: "https://github.com/eclipse-tractusx/puris"
```
